importar bibliotecas que sejam precisas -> vocês vão ter que ter as bibliotecas instaladas ou no anaconda e depois usar aqui ou instalar mesmo no vosso pc, mas depois podemos ver isto juntas

In [5]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

carregar o dataset (que tem de estar na mesma pasta que este notebook)

In [3]:
df = pd.read_csv('online_shoppers_intention.csv')
df.head()

,Administrative,Administrative_Duration,Informational,Informational_Duration,ProductRelated,ProductRelated_Duration,BounceRates,ExitRates,PageValues,SpecialDay,Month,OperatingSystems,Browser,Region,TrafficType,VisitorType,Weekend,Revenue
0,0,0.0,0,0.0,1,0.000000,0.20,0.20,0.0,0.0,Feb,1,1,1,1,Returning_Visitor,False,False
1,0,0.0,0,0.0,2,64.000000,0.00,0.10,0.0,0.0,Feb,2,2,1,2,Returning_Visitor,False,False
2,0,0.0,0,0.0,1,0.000000,0.20,0.20,0.0,0.0,Feb,4,1,9,3,Returning_Visitor,False,False
3,0,0.0,0,0.0,2,2.666667,0.05,0.14,0.0,0.0,Feb,3,2,2,4,Returning_Visitor,False,False
4,0,0.0,0,0.0,10,627.500000,0.02,0.05,0.0,0.0,Feb,3,3,1,4,Returning_Visitor,True,False

ver info toda sobre o dataset (parte 1)

In [2]:
print(f"Número de colunas: {df.shape[1]}")
print(f"Número de linhas: {df.shape[0]}")
print("\nColunas e tipos de dados:\n")
print(df.dtypes)

print("\n" + "="*60)
print("Contagem de valores por coluna")
print("="*60)

for coluna in df.columns:
    print(f"\n--- {coluna} ---")
    print(f"Valores únicos: {df[coluna].nunique()}")
    print(df[coluna].value_counts(dropna=False))

Número de colunas: 18
Número de linhas: 12330

Colunas e tipos de dados:

Administrative               int64
Administrative_Duration    float64
Informational                int64
Informational_Duration     float64
ProductRelated               int64
ProductRelated_Duration    float64
BounceRates                float64
ExitRates                  float64
PageValues                 float64
SpecialDay                 float64
Month                       object
OperatingSystems             int64
Browser                      int64
Region                       int64
TrafficType                  int64
VisitorType                 object
Weekend                       bool
Revenue                       bool
dtype: object

============================================================
Contagem de valores por coluna
============================================================

--- Administrative ---
Valores únicos: 27
Administrative
0     5768
1     1354
2     1114
3      915
4      765
5      575
6      432
7      338
8      287
9      225
10     153
11     105
12      86
13      56
14      44
15      38
16      24
17      16
18      12
19       6
24       4
22       4
23       3
21       2
20       2
27       1
26       1
Name: count, dtype: int64

--- Administrative_Duration ---
Valores únicos: 3335
Administrative_Duration
0.000000      5903
4.000000        56
5.000000        53
7.000000        45
11.000000       42
              ...
65.600000        1
552.200000       1
206.250000       1
401.150000       1
315.966667       1
Name: count, Length: 3335, dtype: int64

--- Informational ---
Valores únicos: 17
Informational
0     9699
1     1041
2      728
3      380
4      222
5       99
6       78
7       36
9       15
8       14
10       7
12       5
14       2
16       1
11       1
24       1
13       1
Name: count, dtype: int64

--- Informational_Duration ---
Valores únicos: 1258
Informational_Duration
0.000000       9925
9.000000         33
10.000000        26
7.000000         26
6.000000         26
               ...
1009.733333       1
216.566667        1
63.100000         1
43.200000         1
17.720000         1
Name: count, Length: 1258, dtype: int64

--- ProductRelated ---
Valores únicos: 311
ProductRelated
1      622
2      465
3      458
4      404
6      396
      ...
378      1
254      1
183      1
210      1
192      1
Name: count, Length: 311, dtype: int64

--- ProductRelated_Duration ---
Valores únicos: 9551
ProductRelated_Duration
0.000000        755
17.000000        21
11.000000        17
8.000000         17
15.000000        16
               ...
4018.450000       1
262.900000        1
4627.489571       1
11431.001240      1
2773.500000       1
Name: count, Length: 9551, dtype: int64

--- BounceRates ---
Valores únicos: 1872
BounceRates
0.000000    5518
0.200000     700
0.066667     134
0.028571     115
0.050000     113
            ...
0.018280       1
0.013620       1
0.000170       1
0.028595       1
0.005980       1
Name: count, Length: 1872, dtype: int64

--- ExitRates ---
Valores únicos: 4777
ExitRates
0.200000    710
0.100000    338
0.050000    329
0.033333    291
0.066667    267
           ...
0.008745      1
0.013132      1
0.002260      1
0.020139      1
0.032193      1
Name: count, Length: 4777, dtype: int64

--- PageValues ---
Valores únicos: 2704
PageValues
0.000000     9600
53.988000       6
42.293068       3
34.039975       2
54.980000       2
             ...
6.094324        1
28.253955       1
16.090650       1
24.897000       1
11.963968       1
Name: count, Length: 2704, dtype: int64

--- SpecialDay ---
Valores únicos: 6
SpecialDay
0.0    11079
0.6      351
0.8      325
0.4      243
0.2      178
1.0      154
Name: count, dtype: int64

--- Month ---
Valores únicos: 10
Month
May     3364
Nov     2998
Mar     1907
Dec     1727
Oct      549
Sep      448
Aug      433
Jul      432
June     288
Feb      184
Name: count, dtype: int64

--- OperatingSystems ---
Valores únicos: 8
OperatingSystems
2    6601
1    2585
3    2555
4     478
8      79
6      19
7       7
5       6
Name: count, dtype: int64

--- Browser ---
Valores únicos: 13
Browser
2     7961
1     2462
4      736
5      467
6      174
10     163
8      135
3      105
13      61
7       49
12      10
11       6
9        1
Name: count, dtype: int64

--- Region ---
Valores únicos: 9
Region
1    4780
3    2403
4    1182
2    1136
6     805
7     761
9     511
8     434
5     318
Name: count, dtype: int64

--- TrafficType ---
Valores únicos: 20
TrafficType
2     3913
1     2451
3     2052
4     1069
13     738
10     450
6      444
8      343
5      260
11     247
20     198
9       42
7       40
15      38
19      17
14      13
18      10
16       3
12       1
17       1
Name: count, dtype: int64

--- VisitorType ---
Valores únicos: 3
VisitorType
Returning_Visitor    10551
New_Visitor           1694
Other                   85
Name: count, dtype: int64

--- Weekend ---
Valores únicos: 2
Weekend
False    9462
True     2868
Name: count, dtype: int64

--- Revenue ---
Valores únicos: 2
Revenue
False    10422
True      1908
Name: count, dtype: int64

ver info toda sobre o dataset (parte 2)

In [3]:
from IPython.display import display

print(f"Número de colunas: {df.shape[1]}")
print(f"Número de linhas: {df.shape[0]}\n")

for coluna in df.columns:
    print(f"--- {coluna} (tipo: {df[coluna].dtype}) ---")
    
    tabela = df[coluna].value_counts(dropna=False).reset_index()
    tabela.columns = ['valor', 'contagem']
    tabela['percentagem'] = (tabela['contagem'] / len(df) * 100).round(2)
    
    display(tabela)
    print()

Número de colunas: 18
Número de linhas: 12330

--- Administrative (tipo: int64) ---

    valor  contagem  percentagem
0       0      5768        46.78
1       1      1354        10.98
2       2      1114         9.03
3       3       915         7.42
4       4       765         6.20
5       5       575         4.66
6       6       432         3.50
7       7       338         2.74
8       8       287         2.33
9       9       225         1.82
10     10       153         1.24
11     11       105         0.85
12     12        86         0.70
13     13        56         0.45
14     14        44         0.36
15     15        38         0.31
16     16        24         0.19
17     17        16         0.13
18     18        12         0.10
19     19         6         0.05
20     24         4         0.03
21     22         4         0.03
22     23         3         0.02
23     21         2         0.02
24     20         2         0.02
25     27         1         0.01
26     26         1         0.01

--- Administrative_Duration (tipo: float64) ---

           valor  contagem  percentagem
0       0.000000      5903        47.88
1       4.000000        56         0.45
2       5.000000        53         0.43
3       7.000000        45         0.36
4      11.000000        42         0.34
...          ...       ...          ...
3330   65.600000         1         0.01
3331  552.200000         1         0.01
3332  206.250000         1         0.01
3333  401.150000         1         0.01
3334  315.966667         1         0.01

[3335 rows x 3 columns]

--- Informational (tipo: int64) ---

    valor  contagem  percentagem
0       0      9699        78.66
1       1      1041         8.44
2       2       728         5.90
3       3       380         3.08
4       4       222         1.80
5       5        99         0.80
6       6        78         0.63
7       7        36         0.29
8       9        15         0.12
9       8        14         0.11
10     10         7         0.06
11     12         5         0.04
12     14         2         0.02
13     16         1         0.01
14     11         1         0.01
15     24         1         0.01
16     13         1         0.01

--- Informational_Duration (tipo: float64) ---

            valor  contagem  percentagem
0        0.000000      9925        80.49
1        9.000000        33         0.27
2       10.000000        26         0.21
3        7.000000        26         0.21
4        6.000000        26         0.21
...           ...       ...          ...
1253  1009.733333         1         0.01
1254   216.566667         1         0.01
1255    63.100000         1         0.01
1256    43.200000         1         0.01
1257    17.720000         1         0.01

[1258 rows x 3 columns]

--- ProductRelated (tipo: int64) ---

     valor  contagem  percentagem
0        1       622         5.04
1        2       465         3.77
2        3       458         3.71
3        4       404         3.28
4        6       396         3.21
..     ...       ...          ...
306    378         1         0.01
307    254         1         0.01
308    183         1         0.01
309    210         1         0.01
310    192         1         0.01

[311 rows x 3 columns]

--- ProductRelated_Duration (tipo: float64) ---

             valor  contagem  percentagem
0         0.000000       755         6.12
1        17.000000        21         0.17
2        11.000000        17         0.14
3         8.000000        17         0.14
4        15.000000        16         0.13
...            ...       ...          ...
9546   4018.450000         1         0.01
9547    262.900000         1         0.01
9548   4627.489571         1         0.01
9549  11431.001240         1         0.01
9550   2773.500000         1         0.01

[9551 rows x 3 columns]

--- BounceRates (tipo: float64) ---

         valor  contagem  percentagem
0     0.000000      5518        44.75
1     0.200000       700         5.68
2     0.066667       134         1.09
3     0.028571       115         0.93
4     0.050000       113         0.92
...        ...       ...          ...
1867  0.018280         1         0.01
1868  0.013620         1         0.01
1869  0.000170         1         0.01
1870  0.028595         1         0.01
1871  0.005980         1         0.01

[1872 rows x 3 columns]

--- ExitRates (tipo: float64) ---

         valor  contagem  percentagem
0     0.200000       710         5.76
1     0.100000       338         2.74
2     0.050000       329         2.67
3     0.033333       291         2.36
4     0.066667       267         2.17
...        ...       ...          ...
4772  0.008745         1         0.01
4773  0.013132         1         0.01
4774  0.002260         1         0.01
4775  0.020139         1         0.01
4776  0.032193         1         0.01

[4777 rows x 3 columns]

--- PageValues (tipo: float64) ---

          valor  contagem  percentagem
0      0.000000      9600        77.86
1     53.988000         6         0.05
2     42.293068         3         0.02
3     34.039975         2         0.02
4     54.980000         2         0.02
...         ...       ...          ...
2699   6.094324         1         0.01
2700  28.253955         1         0.01
2701  16.090650         1         0.01
2702  24.897000         1         0.01
2703  11.963968         1         0.01

[2704 rows x 3 columns]

--- SpecialDay (tipo: float64) ---

   valor  contagem  percentagem
0    0.0     11079        89.85
1    0.6       351         2.85
2    0.8       325         2.64
3    0.4       243         1.97
4    0.2       178         1.44
5    1.0       154         1.25

--- Month (tipo: object) ---

  valor  contagem  percentagem
0   May      3364        27.28
1   Nov      2998        24.31
2   Mar      1907        15.47
3   Dec      1727        14.01
4   Oct       549         4.45
5   Sep       448         3.63
6   Aug       433         3.51
7   Jul       432         3.50
8  June       288         2.34
9   Feb       184         1.49

--- OperatingSystems (tipo: int64) ---

   valor  contagem  percentagem
0      2      6601        53.54
1      1      2585        20.97
2      3      2555        20.72
3      4       478         3.88
4      8        79         0.64
5      6        19         0.15
6      7         7         0.06
7      5         6         0.05

--- Browser (tipo: int64) ---

    valor  contagem  percentagem
0       2      7961        64.57
1       1      2462        19.97
2       4       736         5.97
3       5       467         3.79
4       6       174         1.41
5      10       163         1.32
6       8       135         1.09
7       3       105         0.85
8      13        61         0.49
9       7        49         0.40
10     12        10         0.08
11     11         6         0.05
12      9         1         0.01

--- Region (tipo: int64) ---

   valor  contagem  percentagem
0      1      4780        38.77
1      3      2403        19.49
2      4      1182         9.59
3      2      1136         9.21
4      6       805         6.53
5      7       761         6.17
6      9       511         4.14
7      8       434         3.52
8      5       318         2.58

--- TrafficType (tipo: int64) ---

    valor  contagem  percentagem
0       2      3913        31.74
1       1      2451        19.88
2       3      2052        16.64
3       4      1069         8.67
4      13       738         5.99
5      10       450         3.65
6       6       444         3.60
7       8       343         2.78
8       5       260         2.11
9      11       247         2.00
10     20       198         1.61
11      9        42         0.34
12      7        40         0.32
13     15        38         0.31
14     19        17         0.14
15     14        13         0.11
16     18        10         0.08
17     16         3         0.02
18     12         1         0.01
19     17         1         0.01

--- VisitorType (tipo: object) ---

               valor  contagem  percentagem
0  Returning_Visitor     10551        85.57
1        New_Visitor      1694        13.74
2              Other        85         0.69

--- Weekend (tipo: bool) ---

   valor  contagem  percentagem
0  False      9462        76.74
1   True      2868        23.26

--- Revenue (tipo: bool) ---

   valor  contagem  percentagem
0  False     10422        84.53
1   True      1908        15.47

ver se existem linhas duplicadas (exatamente iguais) e validar se não existem mesmo valores em falta

In [ ]:
# Verificar valores em falta
print("=== Missing Values ===")
missing = df.isnull().sum()
print(missing[missing > 0] if missing.sum() > 0 else "Não existem valores em falta.")

# Verificar duplicados
print("\n=== Duplicados ===")
n_duplicados = df.duplicated().sum()
print(f"Número de linhas duplicadas: {n_duplicados}")

=== Missing Values ===
Não existem valores em falta.

=== Duplicados ===
Número de linhas duplicadas: 125

In [8]:
# Identificar todas as linhas envolvidas em duplicação (originais + cópias)
duplicados = df[df.duplicated(keep=False)].copy()

# Criar um ID de grupo para cada conjunto de linhas idênticas
duplicados['grupo_id'] = duplicados.groupby(list(df.columns)).ngroup()

# Ordenar por grupo para ver os pares/conjuntos lado a lado
duplicados = duplicados.sort_values('grupo_id')

print(f"Total de linhas envolvidas em duplicação: {len(duplicados)}")
print(f"Número de grupos de duplicados distintos: {duplicados['grupo_id'].nunique()}")

Total de linhas envolvidas em duplicação: 201
Número de grupos de duplicados distintos: 76

201 linhas no total fazem parte de algum grupo de duplicados (isto inclui a "primeira ocorrência" de cada grupo + todas as cópias repetidas).
Essas 201 linhas distribuem-se por 76 grupos distintos, ou seja, há 76 combinações de valores diferentes que se repetem, cada uma com 2 ou mais linhas idênticas entre si.